---
kind: pipeline
name: default

steps:
  - name: tags
    image: alpine/git
    commands:
      - git fetch --tags

  - name: lint
    image: golangci/golangci-lint:latest
    commands:
      - make lint

  - name: test
    image: golang:latest
    commands:
      - make test

  - name: build
    image: goreleaser/goreleaser:latest
    commands:
      - make build
    when:
      event:
        exclude:
          - tag

  - name: release
    image: goreleaser/goreleaser:latest
    environment:
      GITHUB_TOKEN:
        from_secret: github_token
    commands:
      - goreleaser release --rm-dist --parallelism=1
    when:
      event:
        - tag
