---
kind: pipeline
type: docker
steps:
  - name: test
    image: golang:1.13
    commands:
      - make test
  - name: lint
    image: golang:1.13
    commands:
      - make lint
  - name: build
    image: golang:1.13
    commands:
      - go get -u github.com/mitchellh/gox
      - make build
  - name: publish
    image: plugins/github-release
    settings:
      api_key:
        from_secret: github_token
      files:
        - fortlit-go_*
    when:
      event: tag
