---
kind: pipeline
type: docker
name: linux-amd64
platform:
  arch: amd64
  os: linux
steps:
  - name: test
    image: golang:1.13.5
    commands:
      - go test ./...
  - name: build
    image: golang:1.13.5
    commands:
      - go build -o fortlit-$(uname -m)
      - ls -la
    environment:
      GOARCH: amd64
      GOOS: linux
  - name: publish
    image: plugins/github-release
    settings:
      api_key:
        from_secret: github_token
      files:
        - fortlit-*
      checksum:
        - md5
        - sha1
        - sha256
        - sha512
        - adler32
        - crc32
    when:
      event: tag
---
kind: pipeline
type: docker
name: linux-arm64
platform:
  arch: arm64
  os: linux
steps:
  - name: build
    image: golang:1.13.5
    commands:
      - go build -o fortlit-$(uname -m)
      - ls -la
    environment:
      GOARCH: arm64
      GOOS: linux
  - name: publish
    image: plugins/github-release
    settings:
      api_key:
        from_secret: github_token
      files:
        - fortlit-*
      checksum:
        - md5
        - sha1
        - sha256
        - sha512
        - adler32
        - crc32
    when:
      event: tag
depends_on:
  - linux-amd64
---
kind: pipeline
type: docker
name: linux-arm
platform:
  arch: arm
  os: linux
steps:
  - name: build
    image: golang:1.13.5
    commands:
      - go build -o fortlit-$(uname -m)
      - ls -la
    environment:
      GOARCH: arm
      GOOS: linux
  - name: publish
    image: plugins/github-release
    settings:
      api_key:
        from_secret: github_token
      files:
        - fortlit-*
      checksum:
        - md5
        - sha1
        - sha256
        - sha512
        - adler32
        - crc32
    when:
      event: tag
depends_on:
  - linux-amd64
